FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

COPY *.sln .
COPY Love.Web/*.csproj ./Love.Web/
COPY Love.Infrastructure/*.csproj ./Love.Infrastructure/
COPY Love.Application/*.csproj ./Love.Application/
COPY Love.Domain/*.csproj ./Love.Domain/

RUN dotnet restore

COPY . .
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:8.0
RUN apt-get update && apt-get install -y libgssapi-krb5-2 && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY --from=build /app/out .

ENV ASPNETCORE_URLS=http://+:80
EXPOSE 80

ENTRYPOINT ["dotnet", "Love.Web.dll"]